### ISSUE TITLE
install error at python 3.6.5

### ISSUE THREAD

**Issue by haolong7** [hkwi/python-geohash#28]
Encountering below error when building wheel for geohash.
```bash
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  sasl/saslwrapper.cpp:249:10: fatal error: 'string' file not found
  #include <string>
           ^~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for sasl
```
I did cmd ```pip install python-geohash```

**Comment by ya9do** [comment]
Hi, @haolong7,
Did you install libsasl2-devel before you try to install `pip install python-geohash`?

I met similar situation because I didn't install python-devel pkg before installing python-geohash.
I think you are trying to install Apache superset and meeting this error (because I am and met this error)

Superset instruction says we need following for CentOS case;
```
sudo yum upgrade python-setuptools
sudo yum install gcc gcc-c++ libffi-devel python-devel python-pip python-wheel openssl-devel libsasl2-devel openldap-devel
```
this command includes libsasl2-devel and the error you met looks like about this pkg.

hope this helps you.

**Comment by haolong7** [comment]
Thank you @ya9do . 

My OS is Mac, by following superset Mac OSX guide, I set both local and venv python version to 3.7.1 first, and at local env brew install the requirements. After that, the error is gone at venv :)

**Comment by jpbirdy** [comment]
hi, @haolong7, I get the same error when I tried to install `pip install sasl`. But I have built it with my MacBook Pro a few months ago. So I guess this error belongs to my XCode version, because I've upgraded it to XCODE 10. When I degrade my XCode to version 9.2, it will be successfully built.

**Comment by ikingye** [comment]
MacOS:
brew install gcc@4.9
env CC=/usr/local/bin/gcc-4.9 pip install thrift_sasl==0.2.1

**Comment by richdevboston** [comment]
WINDOWS 10 Python 3.6 INSTALLATION ISSUE STILL OPEN !!    

Geohash build fails.  Superset package build fails.  It appears that all the other packages build successfully.  

(demo) (base) c:\superset\demo\Scripts>pip install python-geohash
Collecting python-geohash
Using cached https://files.pythonhosted.org/packages/9c/e2/1a3507af7c8f91f8a4975d651d4aeb6a846dfdf74713954186ade4205850/python-geohash-0.8.5.tar.gz
Building wheels for collected packages: python-geohash
Building wheel for python-geohash (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: 'c:\superset\demo\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"'; file='"'"'C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\username\AppData\Local\Temp\pip-wheel-8f2vkeqi' --python-tag cp37
cwd: C:\Users\username\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash
Complete output (22 lines):
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-3.7
copying geohash.py -> build\lib.win-amd64-3.7
copying quadtree.py -> build\lib.win-amd64-3.7
copying jpgrid.py -> build\lib.win-amd64-3.7
copying jpiarea.py -> build\lib.win-amd64-3.7
running build_ext
building '_geohash' extension
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\src
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYTHON_MODULE=1 -Ic:\programdata\anaconda3\include -Ic:\programdata\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /EHsc /Tpsrc/geohash.cpp /Fobuild\temp.win-amd64-3.7\Release\src/geohash.obj
geohash.cpp
src/geohash.cpp(383): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(428): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(429): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(528): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
c:\programdata\anaconda3\include\pyconfig.h(215): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
ERROR: Failed building wheel for python-geohash
Running setup.py clean for python-geohash
Failed to build python-geohash
Installing collected packages: python-geohash
Running setup.py install for python-geohash ... error
ERROR: Command errored out with exit status 1:
command: 'c:\superset\demo\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"'; file='"'"'C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\lysak\AppData\Local\Temp\pip-record-i3ibyuj2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\superset\demo\include\site\python3.7\python-geohash'
cwd: C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash
Complete output (22 lines):
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.7
copying geohash.py -> build\lib.win-amd64-3.7
copying quadtree.py -> build\lib.win-amd64-3.7
copying jpgrid.py -> build\lib.win-amd64-3.7
copying jpiarea.py -> build\lib.win-amd64-3.7
running build_ext
building '_geohash' extension
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\src
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYTHON_MODULE=1 -Ic:\programdata\anaconda3\include -Ic:\programdata\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /EHsc /Tpsrc/geohash.cpp /Fobuild\temp.win-amd64-3.7\Release\src/geohash.obj
geohash.cpp
src/geohash.cpp(383): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(428): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(429): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
src/geohash.cpp(528): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
c:\programdata\anaconda3\include\pyconfig.h(215): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\superset\demo\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"'; file='"'"'C:\Users\lysak\AppData\Local\Temp\pip-install-2_q8h1nq\python-geohash\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\lysak\AppData\Local\Temp\pip-record-i3ibyuj2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\superset\demo\include\site\python3.7\python-geohash' Check the logs for full command output.

(demo) (base) c:\superset\demo\Scripts>

**Comment by Gokulraj1998** [comment]
> Encountering below error when building wheel for geohash.
> 
> ```shell
> warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
>   sasl/saslwrapper.cpp:249:10: fatal error: 'string' file not found
>   #include <string>
>            ^~~~~~~~
>   1 warning and 1 error generated.
>   error: command 'gcc' failed with exit status 1
>   
>   ----------------------------------------
>   Failed building wheel for sasl
> ```
> 
> I did cmd `pip install python-geohash`
same here bro

**Comment by mukhwami** [comment]
Am still having same issue as @richdevboston on windows 10
