### ISSUE TITLE
Failed to build python-geohash

### ISSUE THREAD

**Issue by Abhijeetsinghjat** [hkwi/python-geohash#43]
Getting below error for python-geohash. Can anyone help?

![pythonerror](https://user-images.githubusercontent.com/130652565/234818361-5fff4b0a-453c-48d8-a344-ea0976b21b1f.png)

**Comment by Abhijeetsinghjat** [comment]
@hkwi any help?

**Comment by hkwi** [comment]
The error log says, "C compiler is not installed".

**Comment by Abhijeetsinghjat** [comment]
> The error log says, "C compiler is not installed".

thanks for the help.
